branch-defaults:
  main:
    environment: grafstock-dev
    group_suffix: null
global:
  application_name: grafstock
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: npm run start
